name: PaperMessages
version: '1.0'
main: net.mvndicraft.papermessages.PaperMessages
folia-supported: true
api-version: '1.20'
permissions:
  papermessages.admin:
    description: "Allows use of the reload command."
    default: op