name: PaperMessages
version: '${project.version}'
main: net.euromc.papermessages.MessagesMain
folia-supported: true
api-version: '1.19'
commands:
  reply:
    aliases: [r , rpl]
    usage: /r [content]
  message:
    aliases: [msg, w , whisper , pm]
    usage: /msg [ign] [content]
